"""Added new table and adding foriegn key

Revision ID: 9cb87129a273
Revises: 
Create Date: 2026-06-12 14:26:43.000956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb87129a273'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('onwer_id', sa.Integer(), nullable=False))
    op.alter_column('contacts', 'contact_number',
               existing_type=sa.INTEGER(),
               type_=sa.LargeBinary(),
               postgresql_using='contact_number::bytea',
               existing_nullable=False)
    op.drop_constraint(op.f('contacts_contact_name_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_contact_number_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_user_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['onwer_id'], ['user_id'])
    op.drop_column('contacts', 'user_id')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('users_user_name_key'), 'users', type_='unique')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.add_column('contacts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_user_id_fkey'), 'contacts', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint(op.f('contacts_contact_number_key'), 'contacts', ['contact_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_contact_name_key'), 'contacts', ['contact_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('contacts', 'contact_number',
               existing_type=sa.LargeBinary(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('contacts', 'onwer_id')
    # ### end Alembic commands ###
